
import React, { useEffect, useState, createContext } from "react";
import CommonFormBuilder from "../../CommonComponenets/FormBuilder";
import { localDateTimeString } from "../../../shared/utils/dateFormatter";
import PatientCard from "../../../shared/cards/PatientCard";



/* ---------------- PATIENT CARD ---------------- */
function PatientInformationBlock({ patient, patientHistory, setPatientHistory }) {
  if (!patient) return null;

  const safe = (v) => v ?? "-";
  const formatDate = (d) => d ? new Date(d).toLocaleDateString() : "-";

  return (
    <div style={{ marginBottom: 24 }}>
      <div style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
        gap: 12,
        fontSize: 14
      }}>
        <div><b>Name:</b> {safe(patient.name)}</div>
        <div><b>IC:</b> {safe(patient.id)}</div>
        <div><b>DOB:</b> {formatDate(patient.dob)}</div>

        <div><b>Age / Gender:</b> {safe(patient.age)} / {safe(patient.sex)}</div>
        <div><b>ICD:</b> {safe(patient.icd)}</div>
        <div><b>Date of Assessment:</b> {new Date().toLocaleDateString()}</div>

        <div><b>Date of Onset:</b> {formatDate(patient.date_of_onset)}</div>
        <div><b>Duration of Diagnosis:</b> -</div>
        <div><b>Primary Diagnosis:</b> {safe(patient.diagnosis_history)}</div>

        <div><b>Secondary Diagnosis:</b> {safe(patient.medical_history)}</div>
        <div><b>Dominant Side:</b> {safe(patient.dominant_side)}</div>
        <div><b>Language Preference:</b> {safe(patient.language_preference)}</div>

        <div><b>Education Level:</b> {safe(patient.education_background)}</div>
        <div><b>Occupation:</b> {safe(patient.occupation)}</div>
        <div><b>Work Status:</b> {safe(patient.employment_status)}</div>

        <div><b>Driving Status:</b> {safe(patient.driving_status)}</div>
        <div><b>PP/OB:</b> {safe(patient.pp_ob)}</div>
        <div><b>Weight:</b> {patient.weight ? `${patient.weight} kg` : "-"}</div>

        {/* ===== HISTORY ===== */}
        <div style={{ gridColumn: "1 / -1", marginTop: 10 }}>
        
           <h3>Patient History</h3>
        
                  <div>
                    <b>Past Medical History</b>
                    <input
                      style={input}
                      value={patientHistory.past_medical_history}
                      onChange={(e) =>
                        setPatientHistory(prev => ({
                          ...prev,
                          past_medical_history: e.target.value
                        }))
                      }
                    />
                  </div>

          
          <div>
                    <b>Family History</b>
                    <input
                      style={input}
                      value={patientHistory.past_family_history}
                      onChange={(e) =>
                        setPatientHistory(prev => ({
                          ...prev,
                          past_family_history: e.target.value
                        }))
                      }
                    />
                  </div>

        
           <div>
                    <b>Allergies</b>
                    <input
                      style={input}
                      value={patientHistory.alerts_and_allergies}
                      onChange={(e) =>
                        setPatientHistory(prev => ({
                          ...prev,
                          alerts_and_allergies: e.target.value
                        }))
                      }
                    />
                  </div>

          <button style={alertBtn}>🚨 Alerts</button>
        </div>
      </div>
    </div>
  );
}

/* ---------------- MAIN COMPONENT ---------------- */

const YES_NO = [
  { label: "Yes", value: "yes" },
  { label: "No", value: "no" }
];


export default function PediatricPsychologyProgress({
  patient,
  onSubmit,
  onBack
}) {
  const [values, setValues] = useState({});
  
  const [submitted, setSubmitted] = useState(false);
  const [activeTab, setActiveTab] = useState("subjective");
  const PatientContext = createContext(null);
  const [patientHistory, setPatientHistory] = useState({
    past_medical_history: "",
    past_family_history: "",
    alerts_and_allergies: ""
  });
 
  
 
  const storageKey = patient
    ? `psychology_follow_up_assessment_draft_${patient.id}`
    : null;

  /* LOAD DRAFT */
  useEffect(() => {
    if (!storageKey) return;
    const saved = localStorage.getItem(storageKey);
    if (saved) {
      const parsed = JSON.parse(saved);
      setValues(parsed.values || {});
    }
  }, [storageKey]);

  /* AUTO POPULATE */
 useEffect(() => {
    if (!patient) return;

    setValues(v => ({
      ...v,
      psychiatric_history_autogenerated:
        patient.psychiatric_history || patient.medical_history || "No data available",
      family_medical_history_autogenerated:
        patient.family_history || patient.diagnosis_history || "No data available",
      drug_history_autogenerated:
        patient.medications || patient.drug_history || "No data available"
    }));
  }, [patient]);

  // const onChange = (name, value) => {
  //   setValues(v => ({ ...v, [name]: value }));
  // };

  const onChange = (name, value) => {
  setValues(prev => {
    let updatedValue = value;

    if (Array.isArray(value)) {

      // ✅ NONE logic
      if (
        name === "substance_use"
     
      ) {
        if (value.includes("no_usage")) {
          updatedValue = ["no_usage"];
        } else {
          updatedValue = value.filter(v => v !== "none");
        }
      }

      // ✅ N/A logic
      if (name === "cognition_orientation") {
        if (value.includes("na")) {
          updatedValue = ["na"];
        } else {
          updatedValue = value.filter(v => v !== "na");
        }
      }

      // ✅ Risk Assessment logic
      if (name === "risk_assessment") {
        if (value.includes("no_current_risk")) {
          updatedValue = ["no_current_risk"];
        } else {
          updatedValue = value.filter(v => v !== "no_current_risk");
        }
      }

      // ✅ Drug Review logic (THIS PAGE IMPORTANT)
      if (name === "substance_use") {
        if (value.includes("no_usage")) {
          updatedValue = ["no_usage"];
        } else {
          updatedValue = value.filter(v => v !== "no_usage");
        }
      }
    }

    return {
      ...prev,
      [name]: updatedValue
    };
  });
};

  const handleAction = (type) => {
    if (type === "back") onBack?.();

    if (type === "clear") {
      setValues({});
      setSubmitted(false);
      localStorage.removeItem(storageKey);
    }

    if (type === "save") {
      localStorage.setItem(
        storageKey,
        JSON.stringify({ values, updatedAt: new Date() })
      );
      alert("Psychology draft saved");
    }
  };

  const handleSubmit = () => {
    const status = values.chief_complaint_status
    const text = values.chief_complaint
    if (!text && (status === "modified" || status === "new_complaint") ) {
      alert("Chief Complaint is required")
      return
    }
    setSubmitted(true);
    onSubmit?.(values);
    alert("Psychology assessment submitted");
  };

 

  /* ---------------- SIMPLE SCHEMA (OTHER TABS) ---------------- */
  const EMPTY_SCHEMA = {
    actions: [
      { type: "back", label: "Back" },
      { type: "clear", label: "Clear" },
      { type: "save", label: "Save" }
    ],
    sections: [{ fields: [] }]
  };

const SESSION_SCHEMA = {
    sections: [
      {
        fields: [


          {
            name: "session_type",
            label: "Session Type",
            type: "radio",
            options: [
              { label: "Individual", value: "individual" },
              { label: "Family", value: "family" },
              { label: "Couple", value: "couple" }
            ]
          },

          // {
          //   name: "attendance_status",
          //   label: "Attendance Status",
          //   type: "radio",
          //   options: [
          //     { label: "Present", value: "present" },
          //     { label: "No Show", value: "no_show" },
          //     { label: "Cancelled", value: "cancelled" }
          //   ]
          // },

        {
  name: "attender_present",
  label: "Carer present",
  type: "radio",
  options: [
    { label: "Yes", value: "yes" },
    { label: "No", value: "no" }
  ]
},
{
  name: "attender_name", // ✅ unique
  label: "Specific Name",
  type: "input",
  showIf: {
    field: "attender_present",
    equals: "yes"
  }
},
{
  name: "attender_relationship", // ✅ unique
  label: "Relationship",
  type: "input",
  showIf: {
    field: "attender_present",
    equals: "yes"
  }
},
        ]
      }
    ]
  };


  const SUBJECTIVE_SCHEMA = {
    actions: [
      { type: "back", label: "Back" },
      { type: "clear", label: "Clear" },
      { type: "save", label: "Save" }
    ],
    sections: [
      {
        fields: [
      
          {
  name: "chief_complaint_status",
  label: "Chief Complaint Status",
  type: "radio",
  options: [
    { label: "No Change", value: "no_change" },
    { label: "Modified", value: "modified" }
  ]
},

/* ✅ READ-ONLY FIELD (NO CHANGE) */
{
  name: "chief_complaint_readonly",
  label: "Chief Complaint",
  type: "input",
  placeholder: "No previous complaint available",
  disabled: true,
  showIf: {
    field: "chief_complaint_status",
    equals: "no_change"
  }
},

        


          {
            name: "chief_complaint",
            label: "Chief Complaint",
            required: true,
            type: "input",
            showIf: {
              field: "chief_complaint_status",
              oneOf: ["modified", "new_complaint"]
            }
          },
          {
            name: "hpi",
            label: "History of Presenting Illness (HPI)",
            type: "input"
          },
          
{
  name: "interventions_provided",
  label: "Interventions Provided",
  type: "checkbox-group",   // ✅ dropdown style
  options: [
    { label: "Cognitive-behavioral therapy", value: "cbt" },
    { label: "Behavioral therapy", value: "behavioral_therapy" },
    { label: "Social skills training", value: "social_skills_training" },
    { label: "Interpersonal therapy", value: "interpersonal_therapy" },
    { label: "Play therapy", value: "play_therapy" },
    { label: "Family-based intervention", value: "family_based_intervention" },
    { label: "Expressive art therapy", value: "expressive_art_therapy" },
    { label: "Psychoeducation", value: "psychoeducation" },
    { label: "Parent management training", value: "parent_management_training" },
    { label: "Parent-child interaction therapy", value: "parent_child_interaction_therapy" },
    { label: "Others", value: "others" }
  ]
},
{
  name: "interventions_other",
  label: "Others (Specify)",
  type: "input",
  placeholder: "Enter other interventions...",
  showIf: {
    field: "interventions_provided",
    includes: "others"
  }
},
{
  name: "session_summary",
  label: "Session Summary",
  type: "input",
  placeholder: "Enter summary of the session..."
}

        ]
      }
    ]
  };

  const PSYCHOLOGY_CONTAINER_SCHEMA = {
    title: "Patient Information",
    sections: []
  };

const OBJECTIVE_SCHEMA = {
   actions: [
      { type: "back", label: "Back" },
      { type: "clear", label: "Clear" },
      { type: "save", label: "Save" }
    ],
  name: "objective",
  label: "Objective",
  sections: [
    {
      fields: [
         { type: "subheading", label: "Pediatric MSE Checklist " },
        
        { type: "subheading", label: "1. General Appearance & Behaviour on Entry" },

        /* ===== 1.1 APPEARANCE ===== */
       
        {
          name: "appearance",
          type: "checkbox-group",
          label: "1.1 Appearance",
          options: [
            { label: "Well-groomed / clean", value: "well_groomed" },
            { label: "Unkempt / dishevelled", value: "unkempt" },
            { label: "Bruised / scarred", value: "bruised_scarred" },
            { label: "Not Applicable (N/A)", value: "na" }
          ]
        },
        {
          name: "appearance_na_reason",
          label: "Specify why Not Applicable",
          type: "input",
          showIf: { field: "appearance", includes: "na" }
        },

        /* ===== 1.2 SEPARATION ===== */
       
{
  name: "separation_behavior",
  type: "checkbox-group",
  label: "1.2 Separation behaviour on entry" ,
  options: [
    { label: "Age-appropriate", value: "age_appropriate" },
    { label: "Mild distress", value: "mild_distress" },
    { label: "Significant distress", value: "significant_distress" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "separation_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { 
    field: "separation_behavior", 
    includes: "na"   // ✅ correct for checkbox-group
  }
},

        /* ===== 1.3 INTERACTION ===== */
      
        {
          name: "interaction_clinician",
          type: "checkbox-group",
          label: "1.3 Interaction with clinician",
          options: [
            { label: "Approached readily", value: "approached" },
            { label: "Avoidant", value: "avoidant" },
            { label: "Disinhibited", value: "disinhibited" },
            { label: "Not Applicable (N/A)", value: "na" }
          ]
        },
        {
          name: "interaction_na_reason",
          label: "Specify why Not Applicable",
          type: "input",
          showIf: { field: "interaction_clinician", includes: "na" }
        },
        {
  type: "subheading",
  label: "2. Play Behaviour"
},

/* ================= 2.1 QUALITY OF PLAY ================= */

{
  name: "play_quality",
   label: "2.1 Quality of play",
  type: "checkbox-group",
  
  options: [
    { label: "Functional / relational (uses toys as intended)", value: "functional" },
    { label: "Symbolic / pretend play present", value: "symbolic" },
    { label: "Imaginative / narrative play", value: "imaginative" },
    { label: "Repetitive / stereotyped play", value: "repetitive" },
    { label: "Play absent / no engagement with materials", value: "absent" },
    { label: "Not Applicable (N/A)", value: "na" } // ✅ added
  ]
},
{
  name: "play_quality_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "play_quality", includes: "na" }
},

/* ================= 2.2 SOCIAL PLAY ================= */

{
  name: "play_social",
   label: "2.2 Social dimension of play",
  type: "checkbox-group",
  options: [
    { label: "Solitary play only", value: "solitary" },
    { label: "Parallel play (alongside but not with)", value: "parallel" },
    { label: "Joint / cooperative play", value: "joint" },
    { label: "Directed the clinician in play", value: "directed_clinician" },
    { label: "Followed clinician's lead in play", value: "followed_clinician" },
    { label: "Not Applicable (N/A)", value: "na" } // ✅ added
  ]
},
{
  name: "play_social_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "play_social", includes: "na" }
},

/* ================= 2.3 INITIATION ================= */

{
  name: "play_initiation",
   label: "2.3 Initiation",
  type: "checkbox-group",
  options: [
    { label: "Spontaneous — initiated without prompting", value: "spontaneous" },
    { label: "Required prompting / modelling", value: "prompted" },
    { label: "Did not initiate even with prompting", value: "no_initiation" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "play_initiation_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "play_initiation", includes: "na" } // ✅ FIXED
},

/* ================= 2.4 IMITATION ================= */

{
  name: "play_imitation",
   label: "2.4 Imitation skills",
  type: "checkbox-group", // ✅ single select
  options: [
    { label: "Imitated gestures / actions readily", value: "readily" },
    { label: "Imitation present with delay", value: "delayed" },
    { label: "Imitation absent", value: "absent" },
    { label: "Not Applicable (N/A)", value: "na" } // ✅ added
  ]
},
{
  name: "play_imitation_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "play_imitation", equals: "na" }
},
{
  type: "subheading",
  label: "3. Behavioural Observation"
},

/* ================= 3.1 ACTIVITY LEVEL ================= */

{
  name: "activity_level",
  label: "3.1 Activity level",
  type: "checkbox-group",
  options: [
    { label: "Age-appropriate", value: "age_appropriate" },
    { label: "Hyperactive / restless / fidgety", value: "hyperactive" },
    { label: "Hypoactive / slowed", value: "hypoactive" },
    { label: "Psychomotor agitation", value: "agitation" },
    { label: "Psychomotor retardation", value: "retardation" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "activity_level_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "activity_level", includes: "na" }
},

/* ================= 3.2 COMPLIANCE ================= */

{
  name: "compliance",
  label: "3.2 Compliance & engagement",
  type: "checkbox-group",
  options: [
    { label: "Cooperative", value: "cooperative" },
    { label: "Uncooperative", value: "uncooperative" },
    { label: "Oppositional / defiant", value: "oppositional" },
    { label: "Passive / apathetic", value: "passive" },
    { label: "Demanding / controlling", value: "demanding" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "compliance_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "compliance", includes: "na" }
},

/* ================= 3.3 ATTENTION ================= */

{
  name: "attention_span",
  label: "3.3 Attention span",
  type: "checkbox-group",
  options: [
    { label: "Sustained during preferred / play activity", value: "sustained_play" },
    { label: "Inconsistent — distractible during tasks", value: "inconsistent" },
    { label: "Poor — unable to sustain even briefly", value: "poor" },
    { label: "Appropriate for age", value: "age_appropriate" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "attention_context",
  label: "Document context (e.g., sustained 10 min in play, 2 min task)",
  type: "input"
},
{
  name: "attention_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "attention_span", includes: "na" }
},

/* ================= 3.4 EYE CONTACT ================= */

{
  name: "eye_contact",
  label: "3.4 Eye contact",
  type: "checkbox-group",
  options: [
    { label: "Good / socially appropriate", value: "good" },
    { label: "Poor / avoidant", value: "poor" },
    { label: "Intense / prolonged", value: "intense" },
    { label: "Inconsistent", value: "inconsistent" },
    { label: "Excessive scanning", value: "scanning" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "eye_contact_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "eye_contact", includes: "na" }
},

/* ================= 3.5 MOTOR ================= */

{
  name: "motor_observations",
  label: "3.5 Motor observations",
  
  type: "checkbox-group",
  options: [
    { label: "Motor tics observed", value: "tics" },
    { label: "Tremor", value: "tremor" },
    { label: "Repetitive / stereotyped gestures", value: "stereotypy" },
    { label: "Steady gait", value: "steady_gait" },
    { label: "Unsteady gait", value: "unsteady_gait" },
    { label: "Limping", value: "limping" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "motor_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "motor_observations", includes: "na" }
},
{
  type: "subheading",
  label: "4. Speech & Language"
},

/* ================= 4.1 LANGUAGE LEVEL ================= */

{
  name: "language_level",
  label: "4.1 Language level",
  type: "checkbox-group",
  options: [
    { label: "Age-appropriate", value: "age_appropriate" },
    { label: "Delayed for chronological age", value: "delayed" },
    { label: "Could not assess (non-verbal / selective mutism)", value: "not_assessed" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "language_level_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "language_level", includes: "na" } // ✅ FIXED
},

/* ================= 4.2 RATE & FLOW ================= */

{
  name: "speech_rate_flow",
  label: "4.2 Rate and flow",
  type: "checkbox-group",
  options: [
    { label: "Normal", value: "normal" },
    { label: "Rapid / pressured", value: "rapid" },
    { label: "Slow", value: "slow" },
    { label: "Mute / non-verbal", value: "mute" },
    { label: "Echolalia — immediate", value: "echolalia_immediate" },
    { label: "Echolalia — delayed", value: "echolalia_delayed" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "speech_rate_flow_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "speech_rate_flow", includes: "na" }
},

/* ================= 4.3 QUANTITY ================= */

{
  name: "speech_quantity",
  label: "4.3 Quantity",
  type: "checkbox-group",
  options: [
    { label: "Talkative / spontaneous", value: "talkative" },
    { label: "Impoverished / minimal", value: "minimal" },
    { label: "Expansive", value: "expansive" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "speech_quantity_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "speech_quantity", equals: "na" }
},

/* ================= 4.4 PROSODY ================= */

{
  name: "speech_prosody",
  label: "4.4 Prosody / tone",
  type: "checkbox-group",
  options: [
    { label: "Normal", value: "normal" },
    { label: "Monotonous / flat", value: "flat" },
    { label: "Exaggerated / dramatic", value: "exaggerated" },
    { label: "Loud / raised", value: "loud" },
    { label: "Soft / low", value: "soft" },
    { label: "Anxious tone", value: "anxious" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "speech_prosody_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "speech_prosody", includes: "na" }
},

/* ================= 4.5 FLUENCY ================= */

{
  name: "speech_fluency",
  label: "4.5 Fluency",
  type: "checkbox-group",
  options: [
    { label: "Fluent / clear", value: "fluent" },
    { label: "Stammering / hesitant", value: "stammering" },
    { label: "Dysarthric / articulation errors", value: "dysarthric" },
    { label: "Aphasic", value: "aphasic" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "speech_fluency_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "speech_fluency", includes: "na" }
},

{
  type: "subheading",
  label: "5. Mood & Affect"
},

// {
//   type: "note",
//   label: "For young children: supplement adult mood labels with observable child equivalents below."
// },

/* ================= 5.1 OBSERVED MOOD ================= */

{
  name: "observed_mood",
   label: "5.1 Observed mood",
  type: "checkbox-group",
  options: [
    { label: "Euthymic / content", value: "euthymic" },
    { label: "Anxious / tense", value: "anxious" },
    { label: "Depressed / sad", value: "depressed" },
    { label: "Irritable", value: "irritable" },
    { label: "Euphoric / elated", value: "euphoric" },
    { label: "Apathetic / flat", value: "apathetic" },
    { label: "Angry / dysphoric", value: "angry" },
    { label: "Labile / unstable", value: "labile" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "observed_mood_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "observed_mood", includes: "na" }
},

/* ================= 5.2 CHILD EQUIVALENTS ================= */

{
  name: "child_mood_observation",
  label: "5.2 Observable child equivalents",
  type: "checkbox-group",
  options: [
    { label: "Cried during session", value: "cried" },
    { label: "Smiled / laughed appropriately", value: "smiled" },
    { label: "Showed frustration when task too hard", value: "frustration" },
    { label: "Responded to praise with positive affect", value: "positive_response" },
    { label: "Flat response to social overtures", value: "flat_response" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "child_mood_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "child_mood_observation", includes: "na" }
},

/* ================= 5.3 AFFECT ================= */

{
  name: "affect",
    label: "5.3 Affect",
  type: "checkbox-group",
  options: [
    { label: "Congruent with expressed mood", value: "congruent" },
    { label: "Incongruent", value: "incongruent" },
    { label: "Full range", value: "full_range" },
    { label: "Restricted / constricted", value: "restricted" },
    { label: "Blunted / flat", value: "blunted" },
    { label: "Broad / expansive", value: "broad" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "affect_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "affect", includes: "na" }
},
{
  type: "subheading",
  label: "6. Thought"
},

/* ================= 6.1 FORM / PROCESS ================= */
{
  name: "thought_form",
  label: "6.1 Form / process (inferred from speech and play)",

  type: "checkbox-group",
  options: [
    { label: "Age-appropriate coherence", value: "coherent" },
    { label: "Loose associations", value: "loose_associations" },
    { label: "Tangential", value: "tangential" },
    { label: "Circumstantial", value: "circumstantial" },
    { label: "Flight of ideas", value: "flight_of_ideas" },
    { label: "Poverty of thought", value: "poverty" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "thought_form_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "thought_form", includes: "na" }
},

// {
//   type: "note",
//   label: "Note: Thought insertion, broadcasting, and withdrawal are rare in children — document only with clear evidence."
// },

/* ================= 6.2 CONTENT ================= */

{
  name: "thought_content",
   label: "6.2 Content",
  type: "checkbox-group",
  options: [
    { label: "Age-appropriate fantasy / imagination", value: "fantasy" },
    { label: "Abnormal thought content (describe)", value: "abnormal" },
    { label: "Persecutory / fearful themes in play or speech", value: "persecutory" },
    { label: "Obsessional themes", value: "obsessional" },
    { label: "Suicidal ideation (assess carefully)", value: "suicidal" },
    { label: "Self-harm ideation", value: "self_harm" },
    { label: "Violent themes", value: "violent" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "thought_content_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "thought_content", includes: "na" }
},

/* ===== CONDITIONAL DESCRIPTION FOR ABNORMAL ===== */
{
  name: "thought_content_description",
  label: "Describe abnormal thought content",
  type: "input",
  showIf: { field: "thought_content", includes: "abnormal" }
},

{
  type: "subheading",
  label: "7. Perception"
},

{
  name: "perception",
  label: "Perception",
  type: "checkbox-group",
  options: [
    { label: "No perceptual disturbance noted", value: "none" },
    { label: "Auditory hallucinations (assess carefully — distinguish from imagination/play)", value: "auditory" },
    { label: "Visual hallucinations", value: "visual" },
    { label: "Illusions", value: "illusions" },
    { label: "Derealization / depersonalization (age ≥ 8)", value: "derealization" },
    { label: "Not Applicable (N/A)", value: "na" } // ✅ added
  ]
},

/* ===== N/A REASON ===== */
{
  name: "perception_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "perception", includes: "na" }
},

/* ===== DETAILS FOR ABNORMAL ===== */
{
  type: "subheading",
  label: "8. Sensorium"
},

/* ================= 8.1 CONSCIOUSNESS ================= */

{
  name: "consciousness",
  label: "8.1 Consciousness",
  type: "checkbox-group",
  options: [
    { label: "Alert", value: "alert" },
    { label: "Lethargic / drowsy", value: "drowsy" },
    { label: "Confused", value: "confused" },
    { label: "Clouded", value: "clouded" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "consciousness_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "consciousness", equals: "na" }
},

/* ================= 8.2 ORIENTATION ================= */

{
  name: "orientation",
   label: "8.2 Orientation ⚠ AGE-GATED — apply only if ≥ 7 years",
  type: "checkbox-group",
  options: [
    { label: "Oriented to person", value: "person" },
    { label: "Oriented to place", value: "place" },
    { label: "Oriented to time", value: "time" },
    { label: "Not assessable — age", value: "age_na" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "orientation_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "orientation", includes: "na" }
},

/* ===== OPTIONAL AGE WARNING (if you track age in values) ===== */
{
  name: "orientation_age_note",
  type: "note",
  label: "Orientation testing is typically valid for children ≥ 7 years",
  showIf: { field: "patient_age", lessThan: 7 } // ⚠ requires builder support
},

/* ================= 8.3 MEMORY ================= */

{
  name: "memory",
  label: "8.3 Memory (observe in context)",
  type: "checkbox-group",
  options: [
    { label: "Intact for age", value: "intact" },
    { label: "Mildly impaired", value: "mild" },
    { label: "Moderately impaired", value: "moderate" },
    { label: "Not formally assessed", value: "not_assessed" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},
{
  name: "memory_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "memory", equals: "na" }
},
{
  type: "subheading",
  label: "9. Insight & Judgment"
},

/* ================= 9.1 INSIGHT ================= */

{
  name: "insight",
  label: "9.1 Insight",
  type: "checkbox-group",
  options: [
    { label: "Age-appropriate understanding of difficulties", value: "age_appropriate" },
    { label: "Limited — acknowledges problems only when prompted", value: "limited" },
    { label: "Impaired for developmental level — minimises or denies", value: "impaired" },
    { label: "Not assessable — age / developmental level", value: "not_assessable" },
    { label: "Child able to name what they find difficult", value: "can_describe" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},

/* ===== DOCUMENTATION FIELD ===== */
{
  name: "insight_description",
  label: "Document what the child reports as difficult",
  type: "input",
  showIf: { field: "insight", includes: "can_describe" }
},

/* ===== N/A REASON ===== */
{
  name: "insight_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "insight", includes: "na" }
},

/* ================= 9.2 JUDGMENT ================= */

{
  name: "judgment",
  label: "9.2 Judgment",
  type: "checkbox-group",
  options: [
    { label: "Age-appropriate — makes reasonable choices in play / tasks", value: "age_appropriate" },
    { label: "Limited — impulsive decisions without considering consequences", value: "limited" },
    { label: "Significantly impaired — no awareness of social consequences", value: "impaired" },
    { label: "Not assessable — age", value: "not_assessable" },
    { label: "Not Applicable (N/A)", value: "na" }
  ]
},

/* ===== N/A REASON ===== */
{
  name: "judgment_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "judgment", equals: "na" }
},
{
  type: "subheading",
  label: "10. Caregiver-Observed Behaviour During Session"
},


{
  name: "caregiver_observation",
   label: "10. Caregiver-Observed Behaviour During Session",
  type: "checkbox-group",
  options: [
    {
      label: "Caregiver's description of child's current state matches clinician observation",
      value: "matches"
    },
    {
      label: "Caregiver notes child is 'not themselves today'",
      value: "not_themselves"
    },
    {
      label: "Significant discrepancy between caregiver report and observed behaviour (document)",
      value: "discrepancy"
    },
    {
      label: "Caregiver interaction style noted",
      value: "interaction_style"
    },
    {
      label: "Not Applicable (N/A)",
      value: "na"
    }
  ]
},

/* ===== DISCREPANCY DETAILS ===== */
{
  name: "caregiver_discrepancy_details",
  label: "Describe discrepancy between caregiver report and observed behaviour",
  type: "input",
  showIf: { field: "caregiver_observation", includes: "discrepancy" }
},

/* ===== INTERACTION STYLE ===== */
{
  name: "caregiver_interaction_style",
  label: "Caregiver interaction style",
  type: "checkbox-group",
  options: [
    { label: "Warm", value: "warm" },
    { label: "Dismissive", value: "dismissive" },
    { label: "Anxious", value: "anxious" },
    { label: "Enmeshed", value: "enmeshed" },
    { label: "Disengaged", value: "disengaged" }
  ],
  showIf: { field: "caregiver_observation", includes: "interaction_style" }
},

/* ===== N/A REASON ===== */
{
  name: "caregiver_na_reason",
  label: "Specify why Not Applicable",
  type: "input",
  showIf: { field: "caregiver_observation", includes: "na" }
},
{
  name: "additional_comments",
  label: "Additional comments",
  type: "input",
  placeholder: "Enter any overall observations, notes, or summary..."
},
   

      ]
    },
    
    
    
  ]
};

  const ASSESSMENT_SCHEMA = {
    actions: SUBJECTIVE_SCHEMA.actions,
    sections: [
      {
        fields: [
            // { type: "subheading", label: "Clinical Impression"},
          {
            name: "clinicalImpression",
            label: "Clinical Impression",
            type: "input"
          },
          // { type: "subheading", label: "Clinical Summary"},
          // {
          //   name: "clinical_progress_summary",
          //   label: "Clinical Progress Summary",
          //   type: "input"
          // },
          // { type: "subheading", label: "Diagnosis"},
          // {
          //   name: "severity",
          //   label: "Severity",
          //   type: "radio",
          //   options: [
          //     { label: "Mild", value: "mild" },
          //     { label: "Moderate", value: "moderate" },
          //     { label: "Severe", value: "severe" }
          //   ]
          // },
          
        ]
      }
    ]
  };

  /* ---------------- PLAN SCHEMA WITH GOALS ---------------- */
  const PLAN_SCHEMA = {
    actions: EMPTY_SCHEMA.actions,
    sections: [
      {
        fields: [
           { type: "subheading", label: "Short-Term Goals (2–4 weeks)" },
        {
            type: "dynamic-goals",
            name: "short_term_goals"
          },
          { type: "subheading", label: "Long-Term Goals (6–12 weeks)" },
          {
            type: "dynamic-goals",
            name: "long_term_goals"
          },
          {type:'input',label:'Intervention',name:'intervention'}
         
        ]
      }
    ]
  };
const tabOrder = ["subjective", "objective", "assessment", "plan"];
const activeTabIdx = tabOrder.indexOf(activeTab);

 const schemaMap = {
  subjective: SUBJECTIVE_SCHEMA,
  objective: OBJECTIVE_SCHEMA,
  assessment: ASSESSMENT_SCHEMA,
  plan: PLAN_SCHEMA
};

return (
  <PatientContext.Provider value={patient}>
    <div style={mainContent}>

      {/* PATIENT INFO */}
      <CommonFormBuilder
                schema={{ title: "Patient Information", sections: [] }}
                values={{}}
                onChange={() => {}}
              >
                <PatientInformationBlock
                  patient={patient}
                  patientHistory={patientHistory}
                  setPatientHistory={setPatientHistory}
                />
              
                <button style={doctorsReportBtn}>
                  Doctors Reports
                </button>
              </CommonFormBuilder>
      {/* <CommonFormBuilder
        schema={{ sections: [] }}
        values={{}}
        onChange={() => {}}
      >
        <PatientCard patient={patient} />
      </CommonFormBuilder> */}
{/* ✅ SESSION DETAILS ABOVE TABS */}
        <CommonFormBuilder
          schema={SESSION_SCHEMA}
          values={values}
          onChange={onChange}
        />



      {/* TABS */}
         <div style={tabBar}>
          {["subjective", "objective", "assessment", "plan"].map(tab => (
            <div
              key={tab}
              style={activeTab === tab ? tabActive : tabBtn}
              onClick={() => setActiveTab(tab)}
            >
              {tab.toUpperCase()}
            </div>
          ))}
        </div>

      {/* FORM */}
      <CommonFormBuilder
        schema={schemaMap[activeTab]}
        values={values}
        onChange={onChange}
        submitted={submitted}
        onAction={handleAction}
      >

       

        {/* SUBMIT */}
        
        <div style={submitRow}>
          {activeTab !== "plan" ? (
            <button style={submitBtn} onClick={() => setActiveTab(tabOrder[activeTabIdx + 1])}>
              Next
            </button>
          ) : (
            <button style={submitBtn} onClick={handleSubmit}>
               Submit Psychology Assessment
            </button>
          )}
        </div>

      </CommonFormBuilder>

    </div>
  </PatientContext.Provider>
);
};
/* ---------------- STYLES ---------------- */

const mainContent = { width: "100%" };

const tabBar = {
  display: "flex",
  gap: 12,
  justifyContent: "center",
  borderBottom: "1px solid #ddd",
  marginBottom: 12
};

const tabBtn = {
  padding: "10px 22px",
  fontWeight: 600,
  cursor: "pointer",
  color: "#0f172a"
};

const tabActive = {
  ...tabBtn,
  borderBottom: "3px solid #2451b3",
  color: "#2451b3"
};

const submitRow = {
  display: "flex",
  justifyContent: "flex-end",
  marginTop: 20
};

const submitBtn = {
  padding: "12px 32px",
  background: "#2563EB",
  color: "#fff",
  border: "none",
  borderRadius: 10,
  fontSize: 15,
  fontWeight: 700
};


const section = { marginBottom: 24 };

const patientGrid = {
  display: "grid",
  gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  gap: 12
};
const input = {
          width: "100%",
          minHeight: 90,
          marginTop: 6,
          marginBottom: 12,
          padding: "10px 12px",
          borderRadius: 6,
          border: "1px solid #d1d5db",
          fontSize: 14,
          resize: "vertical"
};
const alertBtn = {
  marginTop: 10,
          padding: "10px 20px",
          borderRadius: 6,
          border: "1.5px solid #007bff",
          background: "#007bff",
          color: "#fff",
          fontWeight: 600,
          cursor: "pointer"
};

const doctorsReportBtn = {
  padding: "10px 20px", background: "#2563EB", color: "#fff",
  border: "none", borderRadius: 6, fontSize: 14,
  fontWeight: 600, cursor: "pointer", marginTop: 8
};