import React, { useEffect, useState, createContext, useContext } from "react";
import CommonFormBuilder from "../../CommonComponenets/FormBuilder";
import { localDateTimeString } from "../../../shared/utils/dateFormatter";

// Create context to pass patient to assessment components
const PatientContext = createContext(null);


function PatientCard({ patient }) {
  if (!patient) return null;

  return (
    <div style={section}>
      <div style={patientGrid}>
        <div><b>Name:</b> {patient.name}</div>
        <div><b>IC:</b> {patient.id}</div>
        <div><b>DOB:</b> {localDateTimeString(patient.dob)}</div>
        <div><b>Age / Gender:</b> {patient.age} / {patient.sex}</div>
        <div><b>ICD:</b> {patient.icd}</div>
        <div><b>Accommodation:</b> {patient.accommodation || "-"}</div>
        <div><b>Occupation:</b> {patient.occupation || "-"}</div>
        <div><b>Case Manager:</b> {patient.case_manager || patient.cm || "-"}</div>
        <div><b>Date of Assessment:</b> {localDateTimeString('', true)}</div>
        <div><b>Date of Encounter/Visit:</b></div>
        <div><b>Visit Type:</b></div>
        <div><b>Session Type:</b></div>
        <div><b>Attendance Status:</b></div>
        <div><b>Others Present:</b></div>
      </div>
    </div>
  );
}

/* ===================== OPTIONS ===================== */

const YES_NO = [
  { label: "Yes", value: "yes" },
  { label: "No", value: "no" }
];

/* ===================== COMPONENT ===================== */

export default function PsychologyFollowUpAssessment({ patient, onSubmit, onBack }) {
  const [values, setValues] = useState({});
  const [submitted, setSubmitted] = useState(false);
  const [activeTab, setActiveTab] = useState("subjective");

  /* ---------------- STORAGE ---------------- */
  const storageKey = patient
    ? `psychology_follow_up_assessment_draft_${patient.id}`
    : null;

  useEffect(() => {
    if (!storageKey) return;
    const saved = localStorage.getItem(storageKey);
    if (saved) {
      setValues(JSON.parse(saved).values || {});
    }
  }, [storageKey]);

  useEffect(() => {
    if (!patient) return;

    setValues(v => ({
      ...v,
      psychiatric_history_autogenerated:
        patient.psychiatric_history || patient.medical_history || "No data available",
      family_medical_history_autogenerated:
        patient.family_history || patient.diagnosis_history || "No data available",
      drug_history_autogenerated:
        patient.medications || patient.drug_history || "No data available"
    }));
  }, [patient]);

  const onChange = (name, value) => {
    setValues(v => ({ ...v, [name]: value }));
  };

  const handleAction = (type) => {
    if (type === "back") onBack?.();

    if (type === "clear") {
      setValues({});
      setSubmitted(false);
      localStorage.removeItem(storageKey);
    }

    if (type === "save") {
      localStorage.setItem(
        storageKey,
        JSON.stringify({ values, updatedAt: new Date() })
      );
      alert("Psychology draft saved");
    }
  };

  const handleSubmit = () => {
    const status = values.chief_complaint_status
    const text = values.chief_complaint
    if (!text && (status === "modified" || status === "new_complaint") ) {
      alert("Chief Complaint is required")
      return
    }
    setSubmitted(true);
    onSubmit?.(values);
    alert("Psychology assessment submitted");
  };

  /* ===================== SCHEMAS ===================== */

  const SUBJECTIVE_SCHEMA = {
    actions: [
      { type: "back", label: "Back" },
      { type: "clear", label: "Clear" },
      { type: "save", label: "Save" }
    ],
    sections: [
      {
        fields: [
          {
            name: "chief_complaint_status",
            label: "Chief Complaint Status",
            type: "radio",
            options: [
              { label: "No Change", value: "no_change"},
              { label: "Modified", value: "modified"},
              { label: "New Complaint", value: "new_complaint"}
            ]
          },
          {
            name: "chief_complaint",
            label: "Chief Complaint",
            required: true,
            type: "textarea",
            showIf: {
              field: "chief_complaint_status",
              oneOf: ["modified", "new_complaint"]
            }
          },
          {
            name: "new_symptoms",
            label: "New Symptoms",
            type: "single-select",
            options: [
              {label: "None", value: "none"},
              {label: "Present", value: "present"}
            ]
          },
          {
            name: "symptoms_category",
            label: "Symptoms Category",
            type: "checkbox-group",
            options: [
              {label: "Mood", value: "mood"},
              {label: "Sleep", value: "sleep"},
              {label: "Appetite", value: "appetite"},
              {label: "Anxiety", value: "anxiety"},
              {label: "Psychosis", value: "psychosis"},
              {label: "Pain", value: "pain"},
              {label: "Others", value: "others"}
            ],
            showIf: {
              field: "new_symptoms",
              equals: "present"
            }
          },
          {
            name: "description",
            label: "Description",
            type: "textarea",
            showIf: {
              field: "symptoms_category",
              equals: "others"
            }
          },
          {
            name: "onset",
            label: "Onset",
            type: "date",
            showIf: {
              field: "new_symptoms",
              equals: "present"
            }
          },
          {
            name: "severity",
            label: "Severity",
            type: "radio",
            options: [
              {label: "Mild", value: "mild"},
              {label: "Moderate", value: "moderate"},
              {label: "Severe", value: "severe"}
            ]
          },
          {type: "subheading", label: "Medication Adherence"},
          {
            name: "fully_adherent",
            label: "Fully Adherent",
            type: "textarea"
          },
          {
            name: "partially_adherent",
            label: "Partially Adherent",
            type: "radio",
            options: [
              {label: "Irregular", value: "irregular"},
              {label: "Missed Doses", value: "missed_doses"}
            ]
          },
          {
            name: "adherent_checkbox",
            type: "checkbox-group",
            options: [
              {label: "Non-Adherent", value: "non_adherent"}
            ]
          },
          {
            name: "reason",
            label: "Reason",
            type: "single-select",
            options: [
              {label: "Forgot", value: "forgot"},
              {label: "Side Effects", value: "side_effects"},
              {label: "Cost Issues", value: "cost_issues"},
              {label: "Lack of Insight", value: "insight_lack"},
              {label: "Intentional Discontinuation", value: "intentional_discontinuation"},
              {label: "Access Issues", value: "access_issues"},
              {label: "Other", value: "other"}
            ],
            showIf: {
              field: "adherent_checkbox",
              equals: "non_adherent"
            }
          },
          {
            name: "description",
            label: "Description",
            type: "textarea",
            showIf: {
              field: "reason",
              equals: "other"
            }
          },
          {
            name: "substance_use",
            label: "Substance Use Update",
            type: "single-select",
            options: [
              {label: "No Use", value: "no_use"},
              {label: "No Change", value: "no_change"},
              {label: "Increased", value: "increased"},
              {label: "Reduced", value: "reduced"},
              {label: "Relapsed", value: "relapsed"},
              {label: "Abstinent", value: "abstinent"}
            ]
          },
          {
            name: "substance_type",
            label: "Substance Type",
            type: "multi-select-dropdown",
            options: [
              {label: "Alcohol", value: "alcohol"},
              {label: "Tobacco", value: "tobacco"},
              {label: "Cannabis", value: "cannabis"},
              {label: "Opioids", value: "opioids"}
            ],
            showIf: {
              field: "substance_use",
              oneOf: ["increased", "relapsed"]
            }
          },
          {
            name: "frequency",
            label: "Frequency",
            type: "radio",
            options: [
              {label: "Daily", value: "daily"},
              {label: "Weekly", value: "weekly"},
              {label: "Occasional", value: "occasional"}
            ],
            showIf: {
              field: "substance_use",
              oneOf: ["increased", "relapsed"]
            }
          },
          {
            name: "quality",
            label: "Quality",
            type: "textarea",
            showIf: {
              field: "substance_use",
              oneOf: ["increased", "relapsed"]
            }
          },
          {
            name: "last_use",
            label: "Last Use",
            type: "date",
            showIf: {
              field: "substance_use",
              oneOf: ["increased", "relapsed"]
            }
          }
        ]
      }
    ]
  };

  const PSYCHOLOGY_CONTAINER_SCHEMA = {
    title: "Patient Information",
    sections: []
  };

  const OBJECTIVE_SCHEMA = {
    actions: SUBJECTIVE_SCHEMA.actions,
    sections: [
      {
        fields: [
          { type: "subheading", label: "Symptom Tracking" },
          {
            name: "mood",
            label: "Mood",
            type: "checkbox-group",
            options: []
          },
          {
            name: "thought_content",
            label: "Thought Content",
            type: "checkbox-group",
            options: []
          },
          {
            name: "perceptual_disturbances",
            type: "checkbox-group",
            options: [
              {label: "Perceptual Disturbances", value: "perceptual_disturbances"}
            ]
          },
          {
            name: "appearance_behaviour",
            label: "Appearance & Behaviour",
            type: "single-select",
            options: [
              {label: "No Change", value: "no_change"},
              {label: "Changed", value: "changed"}
            ]
          },
          {
            name: "details",
            label: "Details",
            type: "textarea",
            showIf: {
              field: "appearance_behaviour",
              equals: "changed"
            }
          },
          {
            name: "speech",
            label: "Speech",
            type: "single-select",
            options: [
              {label: "No Change", value: "no_change"},
              {label: "Changed", value: "changed"}
            ]
          },
          {
            name: "details",
            label: "Details",
            type: "textarea",
            showIf: {
              field: "speech",
              equals: "changed"
            }
          },
          {
            name: "mood_affect",
            label: "Mood & Affect",
            type: "single-select",
            options: [
              {label: "No Change", value: "no_change"},
              {label: "Changed", value: "changed"}
            ]
          },
          {
            name: "details",
            label: "Details",
            type: "textarea",
            showIf: {
              field: "mood_affect",
              equals: "changed"
            }
          },
          {
            name: "thought_process",
            label: "Thought Process",
            type: "single-select",
            options: [
              {label: "No Change", value: "no_change"},
              {label: "Changed", value: "changed"}
            ]
          },
          {
            name: "details",
            label: "Details",
            type: "textarea",
            showIf: {
              field: "thought_process",
              equals: "changed"
            }
          },
          {
            name: "cognition",
            label: "Cognition",
            type: "single-select",
            options: [
              {label: "No Change", value: "no_change"},
              {label: "Changed", value: "changed"}
            ]
          },
          {
            name: "details",
            label: "Details",
            type: "textarea",
            showIf: {
              field: "cognition",
              equals: "changed"
            }
          },
          {type:"subheading", label: "Risk Assessment"},
         {
            name: "risk_assessment",
            label: "Risk Status",
            type: "single-select",
            options: [
              { label: "No risk", value: "no_risk" },
              { label: "Suicidal ideation", value: "suicidal_ideation" },
              { label: "Homicidal ideation", value: "homicidal_ideation" },
              { label: "Self-harm risk", value: "self_harm_risk" },
              { label: "Risk to others", value: "risk_to_others" }
            ]
          },
          {
            name: "risk_checkbox",
            label: "",
            type: "checkbox-group",
            options:[
              {label: "Ideation", value: "ideation"},
              {label: "Plan", value: "plan"},
              {label: "Intent", value: "Intent"},
              {label: "Attempt", value: "attempt"}
            ],
            showIf: {
              field: "risk_assessment",
              oneOf: ["suicidal_ideation", "homicidal_ideation", "self_harm_risk", "risk_to_others"]
            }
          },
          {
            name: "protective_factors",
            label: "Protective Factors",
            type: "textarea",
            showIf: {
              field: "risk_assessment",
              oneOf: ["suicidal_ideation", "homicidal_ideation", "self_harm_risk", "risk_to_others"]
            }
          },
          {
            name: "immediate_action",
            label: "Immediate Action Taken",
            type: "textarea",
            showIf: {
              field: "risk_assessment",
              oneOf: ["suicidal_ideation", "homicidal_ideation", "self_harm_risk", "risk_to_others"]
            }
          },
        ]
      }
    ]
  };

  const ASSESSMENT_SCHEMA = {
    actions: SUBJECTIVE_SCHEMA.actions,
    sections: [
      {
        fields: [
          { type: "subheading", label: "Clinical Summary"},
          {
            name: "clinical_progress_summary",
            label: "Clinical Progress Summary",
            type: "textarea"
          },
          { type: "subheading", label: "Diagnosis"},
          {
            name: "severity",
            label: "Severity",
            type: "radio",
            options: [
              { label: "Mild", value: "mild" },
              { label: "Moderate", value: "moderate" },
              { label: "Severe", value: "severe" }
            ]
          },
          { type: "subheading", label: "Goal Progress"},
          {
            name: "goal_1",
            label: "Goal 1",
            type: "textarea"
          },
          {
            name: "goal_2",
            label: "Goal 2",
            type: "textarea"
          },
          {
            name: "goal_3",
            label: "Goal 3",
            type: "textarea"
          },
          { type: "subheading", label: "Functional Outcome Tracking"},
          {
            name: "social_functioning",
            label: "Social Functioning",
            type: "radio",
            options: [
              {label: "Improved", value: "improved"},
              {label: "Same", value: "same"},
              {label: "Declined", value: "declined"}
            ]
          },
          {
            name: "occupational_functioning",
            label: "Occupational Functioning",
            type: "radio",
            options: [
              {label: "Improved", value: "improved"},
              {label: "Same", value: "same"},
              {label: "Declined", value: "declined"}
            ]
          },
          {
            name: "adl_routine",
            label: "ADL / Routine",
            type: "radio",
            options: [
              {label: "Improved", value: "improved"},
              {label: "Same", value: "same"},
              {label: "Declined", value: "declined"}
            ]
          }
        ]
      }
    ]
  };

  const PLAN_SCHEMA = {
    actions: SUBJECTIVE_SCHEMA.actions,
    sections: [
      {
        fields: [
          {
            type: "subheading", label: "Treatment Plan"
          },
          {
            name: "continue_same_plan",
            label: "Continue Same Plan",
            type: "radio",
            options: [
              {label: "Yes", value: "yes"},
              {label: "No", value: "no"}
            ]
          },
          {
            name: "modify_plan",
            label: "Modify Plan",
            type: "checkbox-group",
            options: [
              {label: "Yes", value: "yes"}
            ]
          },
          {
            name: "details",
            label: "Details",
            type: "textarea",
            showIf: {
              field: "modify_plan",
              equals: "yes"
            }
          },
          {
            name: "care_plan_update",
            label: "Care Plan Update",
            type: "textarea"
          },
          {
            type: "subheading", label: "Risk Management Plan (if applicable)"
          },
          {
            name: "safety_plan_initiated",
            label: "Safety Plan Initiated",
            type: "radio",
            options: [
              {label: "Yes", value: "yes"},
              {label: "No", value: "no"}
            ]
          },
          {
            name: "family_involvement",
            label: "Family Involvement",
            type: "radio",
            options: [
              {label: "Yes", value: "yes"},
              {label: "No", value: "no"}
            ]
          },
          {
            name: "emergency_referral",
            label: "Emergency Referral",
            type: "radio",
            options: [
              {label: "Yes", value: "yes"},
              {label: "No", value: "no"}
            ]
          },
          { type: "subheading", label: "Referrals"},
          {
            name: "psychiatric_referral",
            label: "Psychiatric Referral",
            type: "radio",
            options: [
              {label: "Yes", value: "yes"},
              {label: "No", value: "no"}
            ]
          },
          {
            name: "other_referral",
            label: "Other Referral",
            type: "textarea"
          },
          { type: "subheading", label: "Follow-Up"},
          {
            name: "next_visit_date",
            label: "Next Visit Date",
            type: "date"
          },
          {
            name: "frequency",
            label: "Frequency",
            type: "single-select",
            options: []
          },
          {
            name: "mode",
            label: "Mode",
            type: "radio",
            options: [
              { label: "In-Person", value: "in_person" },
              { label: "Tele", value: "tele" }
            ]
          }
        ]
      }
    ]
  };

  const schemaMap = {
    subjective: SUBJECTIVE_SCHEMA,
    objective: OBJECTIVE_SCHEMA,
    assessment: ASSESSMENT_SCHEMA,
    plan: PLAN_SCHEMA
  };

  /* ===================== PATIENT INFO ===================== */
 

  /* ===================== RENDER ===================== */

  return (
    <PatientContext.Provider value={patient}>
      <div style={mainContent}>
        {/* ===== PATIENT INFORMATION CARD ===== */}
        <CommonFormBuilder
          schema={PSYCHOLOGY_CONTAINER_SCHEMA}
          values={{}}
          onChange={() => {}}
        >
          <PatientCard patient={patient} />
        </CommonFormBuilder>

        {/* ===== TABS ===== */}
        <div style={tabBar}>
          {["subjective", "objective", "assessment", "plan"].map(tab => (
            <div
              key={tab}
              style={activeTab === tab ? tabActive : tabBtn}
              onClick={() => setActiveTab(tab)}
            >
              {tab.toUpperCase()}
            </div>
          ))}
        </div>

        {/* ===== TAB CONTENT ===== */}
        <CommonFormBuilder
          schema={schemaMap[activeTab]}
          values={values}
          onChange={onChange}
          submitted={submitted}
          onAction={handleAction}
        >
          {/* Submit button */}
          <div style={submitRow}>
            <button style={submitBtn} onClick={handleSubmit}>
              Submit 
            </button>
          </div>
        </CommonFormBuilder>
      </div>
    </PatientContext.Provider>
  );
}

/* ===================== STYLES ===================== */

const mainContent = { margin: "0 auto", width: "100%" };

const tabBar = {
  display: "flex",
  gap: 12,
  justifyContent: "center",
  borderBottom: "1px solid #ddd",
  marginBottom: 12
};

const tabBtn = {
  padding: "10px 22px",
  fontWeight: 600,
  cursor: "pointer",
  color: "#0f172a"
};

const tabActive = {
  ...tabBtn,
  borderBottom: "3px solid #2451b3",
  color: "#2451b3"
};

const submitRow = {
  display: "flex",
  justifyContent: "flex-end",
  marginTop: 20
};

const submitBtn = {
  padding: "12px 32px",
  background: "#2563EB",
  color: "#fff",
  border: "none",
  borderRadius: 10,
  fontSize: 15,
  fontWeight: 700
};

const section = {
  marginBottom: 24
};

const patientGrid = {
  display: "grid",
  gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
  gap: 12,
  fontSize: 14
};
